version: 2
updates:
  - package-ecosystem: "github-actions npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      github-actions npm-minor-patch:
        update-types: ["minor", "patch"]

